const models = [
  // === Model: ADAN - NEW ICON ===
  {
    name: "Adan",
    gender: "Boys",
    photo: "../models/boys/adan - new icon/polas/mini/adan_polas 1.webp",
    height: "1.85m",
    measurements: "W 75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8/42",
    availability: "on",
    portfolio: [
      "../models/boys/adan - new icon/book/mini/adan book_01.webp",
      "../models/boys/adan - new icon/book/mini/adan book_02.webp",
      "../models/boys/adan - new icon/book/mini/adan book_03.webp",
      "../models/boys/adan - new icon/book/mini/adan book_04.webp",
      "../models/boys/adan - new icon/book/mini/adan book_05.webp",
      "../models/boys/adan - new icon/book/mini/adan book_06.webp",
      "../models/boys/adan - new icon/book/mini/adan book_07.webp",
      "../models/boys/adan - new icon/book/mini/adan book_08.webp",
      "../models/boys/adan - new icon/book/mini/adan book_09.webp",
      "../models/boys/adan - new icon/book/mini/adan book_10.webp",
      "../models/boys/adan - new icon/book/mini/adan book_11.webp",
      "../models/boys/adan - new icon/book/mini/adan book_12.webp",
      "../models/boys/adan - new icon/book/mini/adan book_13.webp",
      "../models/boys/adan - new icon/book/mini/adan book_14.webp",
      "../models/boys/adan - new icon/book/mini/adan book_15.webp",
      "../models/boys/adan - new icon/book/mini/adan book_16.webp",
      "../models/boys/adan - new icon/book/mini/adan book_17.webp",
      "../models/boys/adan - new icon/book/mini/adan book_18.webp",
      "../models/boys/adan - new icon/book/mini/adan book_19.webp",
      "../models/boys/adan - new icon/book/mini/adan book_20.webp",
      "../models/boys/adan - new icon/book/mini/adan book_21.webp",
      "../models/boys/adan - new icon/book/mini/adan book_22.webp",
      "../models/boys/adan - new icon/book/mini/adan book_23.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas 1.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas2.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas3.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas4.webp",
      //"../models/boys/adan - new icon/polas/mini/adan_polas5.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan6.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan7.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan8.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan9.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan10.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan11.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan12.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan13.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan14.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan15.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan16.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan17.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan18.webp",
      "../models/boys/adan - new icon/polas/mini/polas_adan19.webp",
      //"../models/boys/adan - new icon/polas/mini/polas_adan20.webp",
      "../models/boys/adan - new icon/polas/mini/adan_polas21.webp",
      //"../models/boys/adan - new icon/videos/video_adan_1.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_2.mp4",
      // "../models/boys/adan - new icon/videos/video_adan_3.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_4.mp4",
      //"../models/boys/adan - new icon/videos/video_adan_5.mp4",


    ],
    instagram: []
  }, // === End Model ===

  // === Model: ANGEL BRETT - NEW ICON ===
  {
    name: "Angel",
    gender: "Boys",
    photo: "../models/boys/angel brett - new icon/polas/mini/angel bret__1.webp",
    height: "1.85m",
    measurements: "74cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/42",
    availability: "on",
    portfolio: [
      "../models/boys/angel brett - new icon/book/mini/angel bret book1.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book3.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book4.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book5.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book6.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book7.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book8.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book9.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book10.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book11.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book12.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book13.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book14.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book15.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book16.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book17.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book18.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book19.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book20.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book21.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book22.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book23.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book24.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book25.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book26.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book27.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book28.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book29.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book30.webp",
      "../models/boys/angel brett - new icon/book/mini/angel bret book31.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__2.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__3.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__4.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__5.webp",
      "../models/boys/angel brett - new icon/polas/mini/angel bret__6.webp",
    ],
    instagram: []
  }, // === End Model ===

  /* // === Model: Kevin Rodriguez - Ceres ===
  {
    name: "Kevin Rodriguez",
    gender: "Boys",
    photo: "../models/boys/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    height: "1.88m",
    measurements: "W 77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/44",
    availability: "on",
    portfolio: [
      "../models/boys/kevin rodriguez - ceres/book/mini/1-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/2-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/3-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/4-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/5-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/6-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/7-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/8-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/9-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/10-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/11-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/12-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/13-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/14-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/15-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/16-kevin-rodriguez-main-book-ceres.webp",
      "../models/boys/kevin rodriguez - ceres/book/mini/17-kevin-rodriguez-main-book-ceres.webp",
    ],
    instagram: []
  }, // === End Model === */

  // === Model: Emmanuel ===
  {
    name: "Emmanuel",
    gender: "Boys",
    photo: "../models/boys/emmanuel/polas/mini/emmanuel_polas (1).jpg",
    height: "1.83m",
    measurements: "36",
    hair: "Brown",
    eyes: "hazel",
    shoe: "9/42",
    availability: "on",
    portfolio: [
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_01.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_02.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_03.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_04.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_05.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_06.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_07.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_08.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_09.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_10.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_11.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_12.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_13.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_14.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_15.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_16.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_17.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_18.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_19.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_20.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_21.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_22.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_23.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_24.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_25.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_26.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_27.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_28.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_29.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_30.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_31.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_32.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_33.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_34.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_35.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_36.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_37.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_38.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_39.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_40.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_41.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_42.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_43.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_44.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_45.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_46.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_47.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_48.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_49.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_50.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_51.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_52.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_53.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_54.png",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_55.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_56.jpg",
      "../models/boys/emmanuel/book/full/emmanuel_echavarria_book_57.jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (1).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (10).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (11).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (12).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (13).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (14).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (2).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (3).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (4).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (5).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (6).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (7).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (8).jpg",
      "../models/boys/emmanuel/polas/mini/emmanuel_polas (9).jpg",
    ],
    instagram: []
  }, // === End Model ===


  // === Model: Santiago Poggi - Ceres ===
  {
    name: "Santiago Poggi",
    gender: "Boys",
    photo: "../models/boys/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
    height: "1.88m",
    measurements: "W 65cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "9/43",
    availability: "on",
    portfolio: [
      "../models/boys/santiago poggi - ceres/book/mini/1-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/2-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/3-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/4-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/5-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/6-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/7-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/8-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/9-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/10-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/11-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/12-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/13-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/14-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/15-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/16-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/17-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/18-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/19-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/65-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/50-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/61-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/30-santiago-poggi-2025-ceres.webp",
      "../models/boys/santiago poggi - ceres/book/mini/95-santiago-poggi-2025-ceres.webp",
      //"../models/boys/santiago poggi - ceres/videos/santiago_poggi4.mp4",
      //"../models/boys/santiago poggi - ceres/videos/santiago_poggi5.mp4",
    ],
    instagram: []
  }, // === End Model ===


  // === Model: Maximo ===
  {
    name: "Maximo",
    gender: "Boys",
    photo: "../models/boys/maximo/book/mini/maximo (1).png",
    height: "1.86m",
    measurements: "W 81cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "43",
    availability: "on",
    portfolio: [
      "../models/boys/maximo/book/mini/maximo (1).png",
      "../models/boys/maximo/book/mini/maximo (2).png",
      "../models/boys/maximo/book/mini/maximo (3).png",
      "../models/boys/maximo/book/mini/maximo (4).png",
      "../models/boys/maximo/book/mini/maximo (5).png",
      "../models/boys/maximo/book/mini/maximo (6).png",
      "../models/boys/maximo/book/mini/maximo (7).png",
      "../models/boys/maximo/book/mini/maximo (8).png",
      "../models/boys/maximo/book/mini/maximo (9).png",
      "../models/boys/maximo/book/mini/maximo (10).png",
      "../models/boys/maximo/book/mini/maximo (11).png",
      "../models/boys/maximo/videos/maximo_ video.mp4",

    ],
    instagram: []
  }, // === End Model ===

  // === Model: Alan Marquez ===
  {
    name: "Alan Marquez",
    gender: "Boys",
      photo: "../models/boys/alan marquez/polas/full/alan_marquez_polas (5).jpg",
    height: "1.85m",
    measurements: "Suit 38L",
    hair: "Brown",
    eyes: "Green",
    shoe: "8/42",
    availability: "on",
    portfolio: [
      "../models/boys/alan marquez/book/full/alan_marquez_book_01.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_010.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_011.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_012.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_013.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_014.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_015.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_016.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_017.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_018.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_019.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_02.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_020.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_021.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_022.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_023.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_024.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_025.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_026.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_027.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_028.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_029.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_03.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_030.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_04.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_05.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_06.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_07.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_08.jpg",
      "../models/boys/alan marquez/book/full/alan_marquez_book_09.jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (1).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (2).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (3).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (4).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (5).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (6).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (7).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (8).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (9).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (10).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (11).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (12).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (13).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (14).jpg",
      "../models/boys/alan marquez/polas/full/alan_marquez_polas (15).jpg",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Lucas Tarrago ===
  {
    name: "Lucas Tarrago",
    gender: "Boys",
    photo: "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_01.JPG",
    height: "1.82m",
    measurements: "W 76cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "9.5/43",
    availability: "on",
    portfolio: [
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_01.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_02.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_03.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_04.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_05.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_06.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_07.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_08.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_09.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_10.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_11.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_12.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_13.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_14.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_15.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_16.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_17.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_18.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_19.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_20.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_21.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_22.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_23.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_24.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_25.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_26.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_27.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_28.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_29.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_30.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_31.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_32.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_33.jpg",
      "../models/boys/lucas tarrago/book/full/lucas_tarrago_book_34.jpg",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_01.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_02.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_03.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_04.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_05.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_06.JPG",
      "../models/boys/lucas tarrago/polas/mini/lucas_tarrago_polas_07.JPG",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Belisario ===

  {
		name: "Belisario",
		gender: "Boys",
		photo: "../models/boys/belisario/polas/mini/belisario_polas_ (4).jpeg",
		height: "1.84m",
		measurements: "B 97cm W 83cm H 96cm",
		hair: "Black",
		eyes: "Brown",
		shoe: "44",
    availability: "on",
		portfolio: [
			"../models/boys/belisario/book/mini/belisario_book_01.jpg",
			"../models/boys/belisario/book/mini/belisario_book_02.jpg",
			"../models/boys/belisario/book/mini/belisario_book_03.jpg",
			"../models/boys/belisario/book/mini/belisario_book_04.jpg",
			"../models/boys/belisario/book/mini/belisario_book_05.jpg",
			"../models/boys/belisario/book/mini/belisario_book_06.jpg",
			"../models/boys/belisario/book/mini/belisario_book_07.jpg",
			"../models/boys/belisario/book/mini/belisario_book_08.jpg",
			"../models/boys/belisario/book/mini/belisario_book_09.jpg",
			"../models/boys/belisario/book/mini/belisario_book_10.jpg",
			"../models/boys/belisario/book/mini/belisario_book_11.jpg",
			"../models/boys/belisario/book/mini/belisario_book_12.jpg",
			"../models/boys/belisario/book/mini/belisario_book_13.jpg",
			"../models/boys/belisario/book/mini/belisario_book_14.jpg",
			"../models/boys/belisario/book/mini/belisario_book_15.jpg",
			"../models/boys/belisario/book/mini/belisario_book_16.jpg",
			"../models/boys/belisario/book/mini/belisario_book_17.jpg",
			"../models/boys/belisario/book/mini/belisario_book_18.jpg",
			"../models/boys/belisario/book/mini/belisario_book_19.jpg",
			"../models/boys/belisario/book/mini/belisario_book_20.jpg",
			"../models/boys/belisario/book/mini/belisario_book_21.jpg",
			"../models/boys/belisario/book/mini/belisario_book_22.jpg",
			"../models/boys/belisario/book/mini/belisario_book_23.jpg",
			"../models/boys/belisario/book/mini/belisario_book_24.jpg",
			"../models/boys/belisario/book/mini/belisario_book_25.jpg",
			"../models/boys/belisario/book/mini/belisario_book_26.jpg",
			"../models/boys/belisario/book/mini/belisario_book_27.jpg",
			"../models/boys/belisario/book/mini/belisario_book_28.jpg",
			"../models/boys/belisario/book/mini/belisario_book_29.jpg",
			"../models/boys/belisario/book/mini/belisario_book_30.jpg",
			"../models/boys/belisario/book/mini/belisario_book_31.jpg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (1).jpeg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (2).jpeg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (3).jpeg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (4).jpeg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (5).jpeg",
			"../models/boys/belisario/polas/mini/belisario_polas_ (6).jpeg"
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Felicitas Ceres ===
  {
    name: "Felicitas",
    gender: "Girl",
    photo: "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_1.webp",
    height: "1.76m",
    measurements: "B 81cm W 61cm H 96cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/39.5",
    availability: "on",
    portfolio: [
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_1.webp",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_2.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_3.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_4.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_5.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_6.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_7.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_8.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_9.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_10.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_11.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_12.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_13.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_14.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_15.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_16.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_17.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_18.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_19.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_20.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_21.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_22.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_23.jpg",
      "../models/girls/felicitas - ceres/book/mini/felicitas_codesal_book_24.jpg",
      "../models/girls/felicitas - ceres/polas/mini/felicitas_codesal_book_25.jpg",
      //"../models/girls/felicitas - ceres/polas/mini/10-felicitas-codesal-abril-2025-ceres.webp",
      //"../models/girls/felicitas - ceres/polas/mini/18-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/20-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/26-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/31-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/37-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/42-felicitas-codesal-abril-2025-ceres.webp",
      "../models/girls/felicitas - ceres/polas/mini/50-felicitas-codesal-abril-2025-ceres.webp",
    ]

  }, // === End Model ===



  // === Model: eva - gh ===
  {
    name: "Eva",
    gender: "Girl",
    photo: "../models/girls/eva - gh/polas/mini/eva digitals 01.webp",
    height: "1.75m",
    measurements: "B 79cm W 59cm H 89cm",
    hair: "Brown",
    eyes: "Hazel",
    shoe: "8/38",
    availability: "on",
    portfolio: [
      "../models/girls/eva - gh/book/mini/book01.webp",
      "../models/girls/eva - gh/book/mini/book02.webp",
      "../models/girls/eva - gh/book/mini/book03.webp",
      "../models/girls/eva - gh/book/mini/book04.webp",
      "../models/girls/eva - gh/book/mini/book05.webp",
      "../models/girls/eva - gh/book/mini/book06.webp",
      "../models/girls/eva - gh/book/mini/book07.webp",
      "../models/girls/eva - gh/book/mini/book08.webp",
      "../models/girls/eva - gh/book/mini/book09.webp",
      "../models/girls/eva - gh/book/mini/book010.webp",
      "../models/girls/eva - gh/book/mini/book011.webp",
      "../models/girls/eva - gh/book/mini/book013.webp",
      "../models/girls/eva - gh/book/mini/book014.webp",
      "../models/girls/eva - gh/book/mini/book015.webp",
      "../models/girls/eva - gh/book/mini/book016.webp",
      "../models/girls/eva - gh/book/mini/book017.webp",
      "../models/girls/eva - gh/book/mini/book018.webp",
      "../models/girls/eva - gh/book/mini/book019.webp",
      "../models/girls/eva - gh/book/mini/book020.webp",
      "../models/girls/eva - gh/book/mini/book021.webp",
      "../models/girls/eva - gh/book/mini/book022.webp",
      "../models/girls/eva - gh/book/mini/book023.webp",
      "../models/girls/eva - gh/book/mini/book024.webp",
      "../models/girls/eva - gh/book/mini/book025.webp",
      "../models/girls/eva - gh/book/mini/book026.webp",
      "../models/girls/eva - gh/book/mini/book027.webp",
      "../models/girls/eva - gh/book/mini/book028.webp",
      "../models/girls/eva - gh/book/mini/book029.webp",
      "../models/girls/eva - gh/book/mini/book030.webp",
      "../models/girls/eva - gh/book/mini/book031.webp",
      "../models/girls/eva - gh/book/mini/book032.webp",
      "../models/girls/eva - gh/book/mini/book033.webp",
      "../models/girls/eva - gh/book/mini/book034.webp",
      "../models/girls/eva - gh/book/mini/book035.webp",
      "../models/girls/eva - gh/book/mini/book036.webp",
      "../models/girls/eva - gh/book/mini/book037.webp",
      "../models/girls/eva - gh/book/mini/book038.webp",
      "../models/girls/eva - gh/book/mini/book039.webp",
      "../models/girls/eva - gh/book/mini/book040.webp",
      "../models/girls/eva - gh/book/mini/book041.webp",
      "../models/girls/eva - gh/book/mini/book042.webp",
      "../models/girls/eva - gh/book/mini/book043.webp",
      "../models/girls/eva - gh/book/mini/book044.webp",
      "../models/girls/eva - gh/book/mini/book045.webp",
      "../models/girls/eva - gh/book/mini/book046.webp",
      "../models/girls/eva - gh/book/mini/book047.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 01.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 02.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 03.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 04.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 05.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 06.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 07.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 08.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 09.webp",
      "../models/girls/eva - gh/polas/mini/eva digitals 10.webp",
      //"../models/girls/eva - gh/videos/eva_video1.mp4",
      //"../models/girls/eva - gh/videos/eva_video2.mp4",
    ]
  },

  // === Model: Emilia ===
  {
    name: "Emilia",
    gender: "Girl",
    photo: "../models/girls/emilia bryan/polas/mini/emilia_bryan_polas (1).jpg",
    height: "1.73m",
    measurements: "B 92cm W 60cm H 89cm Dress 2",
    hair: "blonde",
    eyes: "blue",
    shoe: "8/38",
    availability: "on",
    portfolio: [
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_01.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_02.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_03.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_04.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_05.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_06.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_07.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_08.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_09.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_10.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_11.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_12.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_13.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_14.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_15.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_16.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_17.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_18.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_19.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_20.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_21.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_22.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_23.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_24.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_25.jpg",
      "../models/girls/emilia bryan/book/full/emilia_bryan_book_26.jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (1).jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (2).jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (3).jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (4).jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (5).jpg",
      "../models/girls/emilia bryan/polas/full/emilia_bryan_polas (6).jpg",
    ]
  },// === End Model ===

  // === Model: Chloe - New Icon ===
  {
    name: "Chloe",
    gender: "Girl",
    photo: "../models/girls/chloe - new icon/polas/mini/chloe bell pola1.webp",
    height: "1.75m",
    measurements: "B 79cm W 60cm H 89cm",
    hair: "Ginger",
    eyes: "Brown",
    shoe: "40",
    portfolio: [
      "../models/girls/chloe - new icon/book/full/chloe (1).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (10).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (11).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (12).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (13).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (14).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (15).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (16).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (17).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (18).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (19).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (2).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (20).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (21).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (22).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (23).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (24).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (25).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (26).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (27).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (28).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (29).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (3).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (30).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (4).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (5).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (6).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (7).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (8).jpg",
      "../models/girls/chloe - new icon/book/full/chloe (9).jpg",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola1.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola2.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola3.webp",
      "../models/girls/chloe - new icon/polas/mini/chloe bell pola4.webp",
      //"../models/girls/chloe - new icon/videos/Chloe_video.mov",
      //"../models/girls/chloe - new icon/videos/Chloe_video2.mov"
    ],
    instagram: []
  }, // === End Model ===

// === Model: Moana ===
  {
    name: "Moana",
    gender: "Girls",
    photo: "../models/girls/moana/book/mini/moana_buezas_book_01.jpg",
    height: "1.75m",
    measurements: "B 80cm W 63cm H 89cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "6/39",
    availability: "on",
    portfolio: [
      "../models/girls/moana/book/mini/moana_buezas_book_01.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_02.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_03.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_04.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_05.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_06.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_07.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_08.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_09.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_10.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_11.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_12.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_13.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_14.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_15.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_16.jpg",
      "../models/girls/moana/book/mini/moana_buezas_book_17.jpg",
      "../models/girls/moana/polas/mini/moana_polas (1).JPG",
      "../models/girls/moana/polas/mini/moana_polas (2).JPG",
      "../models/girls/moana/polas/mini/moana_polas (3).JPG",
      "../models/girls/moana/polas/mini/moana_polas (4).JPG",
      "../models/girls/moana/polas/mini/moana_polas (5).JPG",
    ],
    instagram: [],
  }, // === End Model ===

  // === Model: Lina ===
  {
    name: "Lina",
    gender: "Girl",
    photo: "../models/girls/lina/polas/mini/lina_polas (1).WEBP",
    height: "1.78m",
    measurements: "B 76cm W 58cm H 80cm",
    hair: "Light Brown",
    eyes: "Blue",
    shoe: "",
    availability: "on",
    portfolio: [
      "../models/girls/lina/book/mini/lina_book (1).jpg",
      "../models/girls/lina/book/mini/lina_book (2).jpg",
      "../models/girls/lina/book/mini/lina_book (3).jpg",
      "../models/girls/lina/book/mini/lina_book (4).jpg",
      "../models/girls/lina/book/mini/lina_book (5).jpg",
      "../models/girls/lina/book/mini/lina_book (6).jpg",
      "../models/girls/lina/book/mini/lina_book (7).jpg",
      "../models/girls/lina/book/mini/lina_book (8).jpg",
      "../models/girls/lina/book/mini/lina_book (9).jpg",
      "../models/girls/lina/book/mini/lina_book (10).jpg",
      "../models/girls/lina/book/mini/lina_book (11).jpg",
      "../models/girls/lina/book/mini/lina_book (12).jpg",
      "../models/girls/lina/book/mini/lina_book (13).jpg",
      "../models/girls/lina/book/mini/lina_book (14).jpg",
      "../models/girls/lina/book/mini/lina_book (15).jpg",
      "../models/girls/lina/book/mini/lina_book (16).jpg",
      "../models/girls/lina/book/mini/lina_book (17).jpg",
      "../models/girls/lina/book/mini/lina_book (18).jpg",
      "../models/girls/lina/book/mini/lina_book (19).jpg",
      "../models/girls/lina/book/mini/lina_book (20).jpg",
      "../models/girls/lina/book/mini/lina_book (21).jpg",
      "../models/girls/lina/book/mini/lina_book (22).jpg",
      "../models/girls/lina/book/mini/lina_book (23).jpg",
      "../models/girls/lina/book/mini/lina_book (24).jpg",
      "../models/girls/lina/book/mini/lina_book (25).jpg",
      "../models/girls/lina/book/mini/lina_book (26).jpg",
      "../models/girls/lina/book/mini/lina_book (27).jpg",
      "../models/girls/lina/book/mini/lina_book (28).jpg",
      "../models/girls/lina/book/mini/lina_book (29).jpg",
      "../models/girls/lina/book/mini/lina_book (30).jpg",
      "../models/girls/lina/book/mini/lina_book (31).jpg",
      "../models/girls/lina/book/mini/lina_book (32).jpg",
      "../models/girls/lina/book/mini/lina_book (33).jpg",
      "../models/girls/lina/book/mini/lina_book (34).jpg",
      "../models/girls/lina/book/mini/lina_book (35).jpg",
      "../models/girls/lina/book/mini/lina_book (36).jpg",
      "../models/girls/lina/book/mini/lina_book (37).jpg",
      "../models/girls/lina/book/mini/lina_book (38).jpg",
      "../models/girls/lina/polas/mini/lina_polas (1).WEBP",
      "../models/girls/lina/polas/mini/lina_polas (2).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (3).WEBP",
      "../models/girls/lina/polas/mini/lina_polas (4).WEBP",
      "../models/girls/lina/polas/mini/lina_polas (5).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (6).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (7).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (8).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (9).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (10).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (11).WEBP",
      "../models/girls/lina/polas/mini/lina_polas (12).WEBP",
      //"../models/girls/lina/polas/mini/lina_polas (13).WEBP",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Alicia Vallecilla ===
  {
    name: "Alicia Vallecilla",
    gender: "Girl",
    photo: "../models/girls/alicia vallecilla - new icon/polas/mini/alicia vallecilla__1.webp",
    height: "1.75m",
    measurements: "B 75cm W 59cm H 89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8.5/39",
    portfolio: [
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_01.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_02.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_03.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_05.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_06.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_07.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_08.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_09.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_10.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_11.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_12.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_13.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_14.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_15.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_16.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_17.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_18.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_19.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_20.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_21.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_22.webp",
      "../models/girls/alicia vallecilla - new icon/book/mini/alicia book_23.webp",
      "../models/girls/alicia vallecilla - new icon/polas/mini/alicia vallecilla__1.webp",
      "../models/girls/alicia vallecilla - new icon/polas/mini/alicia vallecilla__2.webp",
      "../models/girls/alicia vallecilla - new icon/polas/mini/alicia vallecilla__3.webp",
      "../models/girls/alicia vallecilla - new icon/polas/mini/alicia vallecilla__4.webp",
    ],
    instagram: []
  }, // === End Model ===

  // === Model: Luciana Imoberdof - ARG ===
  {
    name: "Luciana Imoberdof",
    gender: "Girl",
    photo: "../models/girls/luciana imoberdof -arg/polas/mini/luciana 01.webp",
    height: "1.78m",
    measurements: "B 76cm W 60cm H 89cm",
    hair: "Blond",
    eyes: "Blue",
    shoe: "9/39",
    availability: "on",
    portfolio: [
      // Book
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book01.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book02.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book03.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book04.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book05.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book06.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book09.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book10.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book11.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book12.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book13.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book14.webp",
      "../models/girls/luciana imoberdof -arg/book/mini/luciana imoberdof book15.webp",
      // Polas
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 01.webp",
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 02.webp",
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 03.webp",
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 06.webp",
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 07.webp",
      "../models/girls/luciana imoberdof -arg/polas/mini/luciana 10.webp",
    ],
    instagram: []
    // === End Model ===

  },

  // === Isabel Deutsch - New Icon ===
  {
    name: "Isabel Deutsch",
    gender: "Girl",
    photo: "../models/girls/isabel deutsch/polas/full/ISABEL-DEUTSCH-POLA-1.jpg",
    height: "1.73m",
    measurements: "B 88cm W 65cm H 90cm",
    hair: "Brown",
    eyes: "Green",
    shoe: "37",
    portfolio: [
      // === Book ===
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-1.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-2.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-3.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-4.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-6.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-8.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-9.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-11.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-13.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-15.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-17.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-19.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-20.jpg",
      "../models/girls/isabel deutsch/book/full/ISABEL-DEUTSCH-PHOTO-21.jpg",
      // === Polas ===
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-1.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-2.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-3.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-4.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-5.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-6.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-7.jpg",
      "../models/girls/isabel deutsch/polas/mini/ISABEL-DEUTSCH-POLA-8.jpg",
    ],
    instagram: []
    // === End Model ===

  },

  // === Model: Agostina Martinez ===
{
		name: "Agostina Martinez",
		gender: "Girl",
    photo: "../models/girls/agostina martinez/polas/mini/agostina_polas (1).JPG",
		height: "1.80m",
		measurements: "B 78cm W 60cm H 89cm",
		hair: "Brown",
		eyes: "Brown",
		shoe: "40",
    availability: "on",
		portfolio: [
			"../models/girls/agostina martinez/book/mini/agostina_book_01.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_02.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_03.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_04.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_05.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_06.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_07.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_08.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_09.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_10.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_11.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_12.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_13.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_14.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_15.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_16.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_17.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_18.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_19.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_20.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_21.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_22.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_23.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_24.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_25.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_26.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_27.jpg",
			"../models/girls/agostina martinez/book/mini/agostina_book_28.jpg",
			"../models/girls/agostina martinez/polas/mini/agostina_polas (1).JPG",
			"../models/girls/agostina martinez/polas/mini/agostina_polas (2).JPG",
			"../models/girls/agostina martinez/polas/mini/agostina_polas (3).JPG",
			"../models/girls/agostina martinez/polas/mini/agostina_polas (4).JPG",
      "../models/girls/agostina martinez/polas/mini/agostina_polas (5).JPG"
    ],
    instagram: []
    // === End Model ===
  },

  // === Model: Doga Bursali ===

	{
		name: "Doga Bursali",
		gender: "Girl",
		photo: "../models/girls/doga bursali/book/mini/doga_book_01.jpg",
		height: "1.78m",
		measurements: "B 75cm W 62cm H 90cm",
		hair: "Brown",
		eyes: "Hazel",
		shoe: "39",
    availability: "on",
		portfolio: [
			"../models/girls/doga bursali/book/mini/doga_book_01.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_02.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_03.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_04.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_05.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_06.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_07.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_08.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_09.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_10.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_11.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_12.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_13.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_14.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_15.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_16.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_17.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_18.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_19.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_20.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_21.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_22.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_23.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_24.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_25.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_26.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_27.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_28.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_29.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_30.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_31.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_32.jpg",
			"../models/girls/doga bursali/book/mini/doga_book_33.jpg",
			"../models/girls/doga bursali/polas/mini/doga_book_ (1).jpeg",
			"../models/girls/doga bursali/polas/mini/doga_book_ (2).jpeg",
			"../models/girls/doga bursali/polas/mini/doga_book_ (3).jpeg",
			"../models/girls/doga bursali/polas/mini/doga_book_ (4).jpeg",
			"../models/girls/doga bursali/polas/mini/doga_book_ (5).jpeg",
      "../models/girls/doga bursali/polas/mini/doga_book_ (6).jpeg"
    ],
    instagram: []
    // === End Model ===
  },

  // === Model: Bernardo Romano ===
  {
    name: "Bernardo",
    gender: "Boys",
    photo: "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_01.jpg",
    height: "181m",
    measurements: "W 31-77cm",
    hair: "Blonde",
    eyes: "Blue",
    shoe: "8/42",
    availability: "on",
    portfolio: [
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_01.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_02.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_03.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_04.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_05.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_06.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_07.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_08.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_09.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_10.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_11.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_12.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_13.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_14.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_15.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_16.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_17.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_18.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_19.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_20.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_21.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_22.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_23.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_24.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_25.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_26.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_27.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_28.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_29.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_30.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_31.jpg",
      "../models/boys/bernardo romano/bernardo romano  book/mini/bernardo_romano_book_32.jpg",
      "../models/boys/bernardo romano/Bernardo polas/mini/bernardo_polas (1).JPG",
      "../models/boys/bernardo romano/Bernardo polas/mini/bernardo_polas (2).jpg",
      "../models/boys/bernardo romano/Bernardo polas/mini/bernardo_polas (3).JPG",
      "../models/boys/bernardo romano/Bernardo polas/mini/bernardo_polas (4).jpg",
      "../models/boys/bernardo romano/Bernardo polas/mini/bernardo_polas (5).JPG",
    ],
    instagram: []
  }, // === End Model ===

// === Model: Santiago Zezular ===
  {
    name: "Santiago Zezular",
    gender: "Hombres",
    photo: "../models/boys/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
    height: "1.87m",
    measurements: "W 75cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "11/45",
    availability: "off",
    portfolio: [
      "../models/boys/santiago zezular - ceres/book/mini/1-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/2-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/3-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/4-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/5-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/6-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/7-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/8-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/9-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/10-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/11-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/12-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/13-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/14-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/15-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/16-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/17-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/18-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/19-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/20-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/21-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/22-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/23-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/book/mini/24-santiago-zezular-main-book-ceres.webp",
      "../models/boys/santiago zezular - ceres/polas/mini/1-santiago-zezular-compolaroid-ceres.webp",
      "../models/boys/santiago zezular - ceres/polas/mini/2-santiago-zezular-compolaroid-ceres.webp",
      //"../models/boys/santiago zezular - ceres/videos/santiago_zezular1.mp4",
      //"../models/boys/santiago zezular - ceres/videos/santiago_zezular2.mp4",

    ],
    instagram: []
  }, // === End Model ===

// === Model: Salih Topcouglu ===
  {
    name: "Salih",
    gender: "Hombres",
    photo: "../models/boys/salih topcouglu/book/mini/salih book1.webp",
    height: "1.88m",
    measurements: "W 77cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "8.5/43",
    availability: "off",
    portfolio: [
      "../models/boys/salih topcouglu/book/mini/salih book1.webp",
      "../models/boys/salih topcouglu/book/mini/salih book2.webp",
      "../models/boys/salih topcouglu/book/mini/salih book3.webp",
      "../models/boys/salih topcouglu/book/mini/salih book4.webp",
      "../models/boys/salih topcouglu/book/mini/salih book5.webp",
      "../models/boys/salih topcouglu/book/mini/salih book6.webp",
      "../models/boys/salih topcouglu/book/mini/salih book7.webp",
      "../models/boys/salih topcouglu/book/mini/salih book8.webp",
      "../models/boys/salih topcouglu/book/mini/salih book9.webp",
      "../models/boys/salih topcouglu/book/mini/salih book10.webp",
      "../models/boys/salih topcouglu/book/mini/salih book11.webp",
      "../models/boys/salih topcouglu/book/mini/salih book12.webp",
      "../models/boys/salih topcouglu/book/mini/salih book13.webp",
      "../models/boys/salih topcouglu/book/mini/salih book14.webp",
      "../models/boys/salih topcouglu/book/mini/salih book15.webp",
      "../models/boys/salih topcouglu/book/mini/salih book16.webp",
      "../models/boys/salih topcouglu/book/mini/salih book17.webp",
      "../models/boys/salih topcouglu/book/mini/salih book18.webp",
      "../models/boys/salih topcouglu/book/mini/salih book19.webp",
      "../models/boys/salih topcouglu/book/mini/salih book20.webp",
      "../models/boys/salih topcouglu/book/mini/salih book21.webp",
      "../models/boys/salih topcouglu/book/mini/salih book22.webp",
      "../models/boys/salih topcouglu/book/mini/salih book23.webp",
      "../models/boys/salih topcouglu/book/mini/salih book24.webp",
      "../models/boys/salih topcouglu/book/mini/salih book25.webp",
      "../models/boys/salih topcouglu/book/mini/salih book26.webp",
      "../models/boys/salih topcouglu/book/mini/salih book27.webp",
      "../models/boys/salih topcouglu/book/mini/salih book28.webp",
      "../models/boys/salih topcouglu/book/mini/salih book29.webp",
      "../models/boys/salih topcouglu/book/mini/salih book30.webp",
      "../models/boys/salih topcouglu/polas/mini/salih polas.webp",
      //"../models/boys/salih topcouglu/videos/salih_video1.mov",
      //"../models/boys/salih topcouglu/videos/salih_video2.MP4",
      //"../models/boys/salih topcouglu/videos/salih_video3.MP4",
    ],
    instagram: []
  }, // === End Model ===

 // === Model: Pilar Sampaio ===
  {
    name: "Pilar",
    gender: "Girls",
    photo: "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_01.jpg",
    height: "1.74m",
    measurements: "B 76cm W 63cm H 85cm",
    hair: "Blonde",
    eyes: "Brown",
    shoe: "6/39",
    availability: "off",
    portfolio: [
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_01.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_02.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_03.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_04.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_05.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_06.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_07.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_08.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_09.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_10.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_11.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_12.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_13.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_14.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_15.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_16.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_17.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_18.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_19.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_20.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_21.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_22.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_23.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_24.jpg",
      "../models/girls/pilar sampaio/Pilar Sampaio book aura/mini/pilar_sampaio_book_25.jpg",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (1).JPG",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (2).JPG",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (3).JPG",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (4).JPG",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (5).JPG",
      "../models/girls/pilar sampaio/Pilar polas/mini/pilar_polas (6).JPG",
    ],
    instagram: [],
  }, // === End Model ===

  // === Model: Genesis - New Icon  ===
  {
    name: "Genesis",
    gender: "girls",
    photo: "../models/girls/genesis  - new icon/polas/mini/genesis polas1.webp",
    height: "5'9.5-1,76m",
    measurements: "B 30.5-78cm W 24-60cm H 35-89cm",
    hair: "Black",
    eyes: "Brown",
    shoe: "8/38",
    availability: "off",
    portfolio: [
      "../models/girls/genesis  - new icon/book/mini/genesis book_01.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_02.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_03.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_04.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_05.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_06.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_07.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_08.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_09.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_10.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_11.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_12.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_13.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_14.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_15.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_16.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_17.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_18.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_19.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_20.webp",
      "../models/girls/genesis  - new icon/book/mini/genesis book_21.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas1.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas2.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas3.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas4.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas5.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas6.webp",
      "../models/girls/genesis  - new icon/polas/mini/genesis polas7.webp",
      //"../models/girls/genesis  - new icon/videos/GENESIS-VIDEO-1.mp4",
    ]
  },
// === Model: Mariana Arias ===
  {
    name: "Mariana Arias",
    gender: "Girl",
    photo: "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
    height: "1.75m",
    measurements: "B 75.5cm W 60cm H 88cm",
    hair: "Brown",
    eyes: "Brown",
    shoe: "7-38",
    availability: "off",
    portfolio: [
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_1.webp",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_2.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_3.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_4.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_5.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_6.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_7.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_8.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_9.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_10.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_11.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_12.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_13.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_14.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_15.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_16.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_17.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_18.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_19.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_20.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_21.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_22.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_23.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_24.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_25.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_26.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_27.jpg",
      "../models/girls/mariana-arias-new-icon/book/full/mariana_arias_book_28.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_1.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_2.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_3.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_4.jpg",
      "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_5.jpg",
      // "../models/girls/mariana-arias-new-icon/polas/full/mariana_arias_polas_6.jpg",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_1.mp4",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_2.mp4",
      //"../models/girls/mariana-arias-new-icon/videos/mariana_arias_video_3.mp4",
    ]
  },
];

